version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.11
    working_directory: /go/src/github.com/nanovms/ops
    environment:
      TEST_RESULTS: /tmp/test-results
    steps:
      - checkout
      - run: sudo apt-get install qemu
      - run: make deps
      - run: mkdir -p $TEST_RESULTS
      - run:
          name : run unit tests
          command: |
            trap "go-junit-report <${TEST_RESULTS}/go-test.out > ${TEST_RESULTS}/go-test-report.xml" EXIT
            make test | tee ${TEST_RESULTS}/go-test.out
  build-mac:
    macos:
        xcode: "9.0" 
    steps:
      - checkout
      - run: CI=1 /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
      - run: brew update && brew install go qemu
      - run: make deps
      - run: mkdir -p $TEST_RESULTS
      - run:
          name: macbuild
          command: |
            trap "go-junit-report <${TEST_RESULTS}/go-test.out > ${TEST_RESULTS}/go-test-report.xml" EXIT
            make test | tee ${TEST_RESULTS}/go-test.out
